### PR TITLE
fix/improve_clients_stop_function

### PR DESCRIPTION
**Pull request by tretmar**
In the previous version, they introduced a cleanup channel and wait until the websocket client calls the disconnect handler until leaving the `Stop()` function.

In our unit tests however, this failed when running with `goleak.VerifyNone(t)`.

Investigating it further, it turned out that the `DisconnectHandler` is not called when the websocket client is stopped using the `Stop()` function with was done here.

**Documentation:**
```
Sets a callback function for receiving notifications about an unexpected disconnection from the server.
The callback is invoked even if the automatic reconnection mechanism is active.

If the client was stopped using the Stop function, the callback will NOT be invoked.
```

See
https://github.com/grid-x/ocpp-go/blob/c020c2b1039ad5191ac3b23c049b7e50efbff648/ws/websocket.go#L692

### CODE REVIEW

**Comment by guelfey** [comment]
weird, did we change something in [ocpp-go/ws/websocket.go](https://github.com/grid-x/ocpp-go/blob/c020c2b1039ad5191ac3b23c049b7e50efbff648/ws/websocket.go#L692) that wasn't upstreamed?

**Comment by tretmar** [comment]
> weird, did we change something in [ocpp-go/ws/websocket.go](https://github.com/grid-x/ocpp-go/blob/c020c2b1039ad5191ac3b23c049b7e50efbff648/ws/websocket.go#L692) that wasn't upstreamed?

nope, this is something, that was done in upstream on January 2022.
See https://github.com/lorenzodonini/ocpp-go/commit/b8ece474fe4f4eed0adf4809530c85fd111d49a9

**Comment by guelfey** [comment]
yes I found that, but wondered why it didn't cause issues upstream; if we made some changes in other files that interacted with this part, but weren't upstreamed, that could be an explanation. (Or it just wasn't noticed.)

**Comment by tretmar** [comment]
It only caused our unit tests in the client repository to fail. In the OCPP unit tests, there is always `goleak.VerifyNone(t)` included which checks for unfinished goroutines.

**Review by guelfey — APPROVED** [review]

**Pull request merged**
